### PR TITLE
Switch from nerves_uart to circuits_uart.

### PR DESCRIPTION
**Pull request by jimsynz**
The maintainers of several Nerves packages that aren't Nerves-specific (like `I2C`, `SPI`, etc) have been migrating them to the [Elixir Circuits](https://elixir-circuits.github.io/) project which is more robust.

This PR basically replaces any mention of `Nerves` with `Circuits`. No other changes need be made.

Additionally, one of the tests doesn't pass, but it's not passing on master either.

### CODE REVIEW

**Comment by jimsynz** [comment]
@entone any chance you can give me an update as to whether this is likely to be accepted?

**Comment by entone** [comment]
@jimsynz so sorry, not sure how this slipped past. I will review and get back to you soon.

**Comment by entone** [comment]
@jimsynz I'm seeing a failing test when using your branch.

```
1) test compatibility_response (Firmata.Protocol.Sysex.SysexTest)
     test/firmata/protocol/sysex/sysex_test.exs:41
     Assertion with == failed
     code:  assert capability_response(@sysex)[:pins] == @pins
     left:  [
              [supported_modes: [11, 6, 4, 2, 1, 0], mode: 16],
              [supported_modes: [11, 6, 4, 2, 1, 0], mode: 16],
              [supported_modes: [11, 4, 2, 1, 0], mode: 16],
              [supported_modes: [11, 4, 2, 1, 0], mode: 16],
              [supported_modes: [11, 4, 2, 1, 0], mode: 16],
              [supported_modes: [11, 4, 2, 1, 0], mode: 16],
              [supported_modes: [11, 4, 1, 0], mode: 16],
              [supported_modes: [11, 4, 1, 0], mode: 16],
              [supported_modes: [11, 4, 3, 1, 0], mode: 16],
              [supported_modes: [11, 4, 3, 1, 0], mode: 16],
              [supported_modes: [11, 4, 3, 1, 0], mode: 16],
              [supported_modes: [11, 4, 1, 0], mode: 16],
              [supported_modes: [11, 4, 1, 0], mode: 16],
              [supported_modes: [11, 4, 3, 1, 0], mode: 16],
              [supported_modes: [11, 4, 3, 1, 0], mode: 16],
              [supported_modes: [11, 4, 1, 0], mode: 16],
              [supported_modes: [11, 4, 3, 1, 0], mode: 16],
              [supported_modes: [11, 4, 1, 0], mode: 16],
              [supported_modes: '', mode: 16],
              [supported_modes: '', mode: 16]
            ]
     right: [
              [supported_modes: [6, 4, 2, 1, 0], mode: 16],
              [supported_modes: [6, 4, 2, 1, 0], mode: 16],
              [supported_modes: [4, 2, 1, 0], mode: 16],
              [supported_modes: [4, 2, 1, 0], mode: 16],
              [supported_modes: [4, 2, 1, 0], mode: 16],
              [supported_modes: [4, 2, 1, 0], mode: 16],
              [supported_modes: [4, 1, 0], mode: 16],
              [supported_modes: [4, 1, 0], mode: 16],
              [supported_modes: [4, 3, 1, 0], mode: 16],
              [supported_modes: [4, 3, 1, 0], mode: 16],
              [supported_modes: [4, 3, 1, 0], mode: 16],
              [supported_modes: [4, 1, 0], mode: 16],
              [supported_modes: [4, 1, 0], mode: 16],
              [supported_modes: [4, 3, 1, 0], mode: 16],
              [supported_modes: [4, 3, 1, 0], mode: 16],
              [supported_modes: [4, 1, 0], mode: 16],
              [supported_modes: [4, 3, 1, 0], mode: 16],
              [supported_modes: [4, 1, 0], mode: 16],
              [supported_modes: '', mode: 16],
              [supported_modes: '', mode: 16]
            ]
     stacktrace:
       test/firmata/protocol/sysex/sysex_test.exs:42: (test)
```

**Comment by kfatehi** [comment]
Yeah, fails in the same way too, "11" added to every "Supported mode"

image

I tried to understand what my whole idea was with respect to that test by looking here http://firmata.org/wiki/V2.3ProtocolDetails#Capability_Query to no avail, sorry.

**Comment by kfatehi** [comment]
@entone I was able to read the full changeset and it looks pretty much code-style/formatting improvements; but I am curious @jimsynz why the dependency count increased by 3? (nimble_parsec looks awesome btw)

**Pull request closed without merging**
